modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"

[[mods]]
modId="electrona"
version = "${file.jarVersion}"
displayName="Electrona"
credits="Credits are on mod's page."
displayURL="https://max094reikeb.github.io/Electrona-Project/"
authors="Max094_Reikeb"
description='''
Electrona is a tech mod made by Max094_Reikeb.

It was originally made on MCreator, but then, the r2.0 version ported it off.
'''

[[dependencies.electrona]] #optional
    modId="forge"
    mandatory=true
    versionRange="[40.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.electrona]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.electrona]]
    modId="terrablender"
    mandatory=true
    versionRange="[1.18.2-1.1.0.99,1.18.2-1.1.0.100)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.electrona]]
    modId="maxilib"
    mandatory=true
    versionRange="[1.18.2-r1.1.1,1.18.2-r1.2]"
    ordering="AFTER"
    side="BOTH"